on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.65.0
        features:
          - --features=std
          - --no-default-features --features=alloc,ahash
        experimental: [false]
        include:
          - rust: nightly
            features: --features=std
            experimental: true
          - rust: nightly
            features: --no-default-features --features=alloc,ahash
            experimental: true
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cargo check
        run: cargo check --all-targets ${{ matrix.features }}

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.65.0
        features:
          - --features=std
          - --no-default-features --features=alloc,ahash
        experimental: [false]
        include:
          - rust: nightly
            features: --features=std
            experimental: true
          - rust: nightly
            features: --no-default-features --features=alloc,ahash
            experimental: true
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run tests
        run: cargo test ${{ matrix.features }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.65.0
        experimental: [false]
        include:
          - rust: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-targets ${{ matrix.features }} -- -D warnings
